spring.application.name=demo

# H2 内存数据库连接
spring.datasource.url=jdbc:h2:mem:demo
spring.datasource.driver-class-name=org.h2.Driver
spring.datasource.username=sa
spring.datasource.password=

# 根据实体创建表，应用结束时删除表
spring.jpa.hibernate.ddl-auto=create-drop

# 在终端显示执行的 SQL
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.format_sql=true

# 关闭请求期间的额外数据库会话
spring.jpa.open-in-view=false
